package pojos;
// Generated 18/08/2012 10:35:17 by Hibernate Tools 3.2.1.GA



/**
 * Evento generated by hbm2java
 */
public class Evento  implements java.io.Serializable {


     private Integer eventoId;
     private String nomePalestra;
     private String nomePalestrante;
     private String local;
     private String horaInicio;
     private String horaFim;
     private String data;
     private String curriculoPalestrante;
     private String sobre;

    public Evento() {
    }

    public Evento(String nomePalestra, String nomePalestrante, String local, String horaInicio, String horaFim, String data, String curriculoPalestrante, String sobre) {
       this.nomePalestra = nomePalestra;
       this.nomePalestrante = nomePalestrante;
       this.local = local;
       this.horaInicio = horaInicio;
       this.horaFim = horaFim;
       this.data = data;
       this.curriculoPalestrante = curriculoPalestrante;
       this.sobre = sobre;
    }
   
    public Integer getEventoId() {
        return this.eventoId;
    }
    
    public void setEventoId(Integer eventoId) {
        this.eventoId = eventoId;
    }
    public String getNomePalestra() {
        return this.nomePalestra;
    }
    
    public void setNomePalestra(String nomePalestra) {
        this.nomePalestra = nomePalestra;
    }
    public String getNomePalestrante() {
        return this.nomePalestrante;
    }
    
    public void setNomePalestrante(String nomePalestrante) {
        this.nomePalestrante = nomePalestrante;
    }
    public String getLocal() {
        return this.local;
    }
    
    public void setLocal(String local) {
        this.local = local;
    }
    public String getHoraInicio() {
        return this.horaInicio;
    }
    
    public void setHoraInicio(String horaInicio) {
        this.horaInicio = horaInicio;
    }
    public String getHoraFim() {
        return this.horaFim;
    }
    
    public void setHoraFim(String horaFim) {
        this.horaFim = horaFim;
    }
    public String getData() {
        return this.data;
    }
    
    public void setData(String data) {
        this.data = data;
    }
    public String getCurriculoPalestrante() {
        return this.curriculoPalestrante;
    }
    
    public void setCurriculoPalestrante(String curriculoPalestrante) {
        this.curriculoPalestrante = curriculoPalestrante;
    }
    public String getSobre() {
        return this.sobre;
    }
    
    public void setSobre(String sobre) {
        this.sobre = sobre;
    }




}


